# Generated by Django 4.2 on 2023-04-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anbardari', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gozaresh',
            new_name='GozareshModel',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductsModel',
        ),
    ]
