# Generated by Django 4.2 on 2023-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anbardari', '0002_rename_gozaresh_gozareshmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
