# Generated by Django 4.2 on 2023-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anbardari', '0003_alter_productsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='expire_date',
            field=models.DateTimeField(help_text="enter the item's price"),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='number',
            field=models.IntegerField(help_text='enter the number of goods'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(help_text="enter the item's price"),
        ),
    ]
