# Generated by Django 4.2 on 2023-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel_Foroosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('price', models.IntegerField(help_text="enter the item's price")),
                ('number', models.IntegerField(help_text='enter the number of goods')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(help_text="enter the item's price")),
            ],
        ),
    ]
